[theme]
base = "dark"
primaryColor = "#42DCA1"
backgroundColor = "#090D12"
secondaryBackgroundColor = "#121923"
textColor = "#E6EAF0"
linkColor = "#73A6FF"
font = "sans serif"
baseRadius = "medium"
borderColor = "#222C39"
showSidebarBorder = true
